kind: Deployment
apiVersion: extensions/v1beta1
metadata:
   name: {{ template "my-docker.fullname" . }}-deployment
spec:
    replicas: 1
    selector:
        matchLabels:
            app: {{ template "my-docker.fullname" . }}-my-docker-application
    template:
        metadata:
            labels:
                app: {{ template "my-docker.fullname" . }}-my-docker-application
        spec:
            containers:
                - name: my-docker-application
                  image: my-docker-application:1.0.0
---
kind: Service
apiVersion: v1
metadata:
    name: {{ template "my-docker.fullname" . }}-service
spec:
    type: NodePort
    selector:
        app: {{ template "my-docker.fullname" . }}-my-docker-application
    ports:
        - port: 8080
          targetPort: 80